### ISSUE TITLE
Раздел проектов: доработать фикстуры и процесс предварительной загрузки фикстур в БД

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/Backend#155]
Загрузить проекты в БД

**Comment by Badmajor** [comment]
Добавлена команда add_fake_users.
Флаги:
-s SAVE, --save SAVE  :str. Save id, email, username and password to <path_to_file.csv>. Default None. 
  -a AMOUNT, --amount AMOUNT :int. Number of users. Default 1
  
 На каждого пользователя создается и профиль

**Comment by Badmajor** [comment]
~Добавлена команда add_fake_profiles.~
~Флаги:~
~-a AMOUNT, --amount AMOUNT :int. Number of profiles. Default 1~
 
~Если юзеров или профессий не хватает для создания нужного количествао профилей, создает нужное количество.~

**Comment by Badmajor** [comment]
Добавлена команда add_fake_projects.
Флаги:
-a AMOUNT, --amount AMOUNT :int. Number of profiles. Default 1

**Comment by Badmajor** [comment]
В ветке add/fixture добавли фикстуры проектов, пользователей и все полные фикстуры(чтобы быстро наполнить проект)
