### ISSUE TITLE
PUT /api/v1/projects/id/: В поле "description" можно отправить иероглифы, код и статус ответа 200 ОК

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Backend#204]
### **Шаги воспроизведения:**

1. Отправить запрос на редактирование проекта с иероглифами для поля "description":
```
  curl --location --request PUT 'https://testcodepet.tw1.ru/api/v1/projects/2/' \
--header 'Authorization: Token e5cf867ddd6134f604b7c77b0a06384ea944a595' \
--header 'Content-Type: application/json' \
--data-raw '{
  "name": "ХъВ г",
  "description": "文字整  式 现文整 无字字文出文  字形文的形 式的 字    整 字 字形 字形法文  的式文形呈的文法呈现字式 呈",
  "started": "2024-4-24",
  "ended": "2024-4-26",
  "busyness": 1,
  "directions": [
    1
  ],
  "link": "https://test.ru",
  "phone_number": "+77837006759",
  "telegram_nick": "Bk_odUveRe7YoqmRj6yt__nL12hAluHM",
  "email": "user@example.com",
  "project_specialists": [
    {
      "profession": 1,
      "skills": [
        1
      ],
      "count": 1,
      "level": 1,
      "is_required": true
    }
  ],
  "status": 2
}'
```

### **Ожидаемый результат:**

В поле "description" нельзя отправить иероглифы. Код и статус ответа 400 Bad request.

### **Фактический результат:**

В поле "description" можно отправить иероглифы. Код и статус ответа 200 OK.

### **Окружение:**

* Сервер: [https://testcodepet.tw1.ru](https://testcodepet.tw1.ru/)
* Приложение: Postman v10.24.22
* ОС: Windows 11 22000.1098

### Приложение:
![image](https://github.com/Pet-projects-CodePET/Backend/assets/32541462/6c32d7c5-82e9-4717-9c83-30afb8aa957b)

**Comment by ArtemKAF** [comment]
Внес изменения в валидацию email адресов везде в проетке (на данный момент) где встречается поле email применяется кастомная валидация, усиливающая проверки стандартным валидатором джанго.
Можно прогнать тесты еще раз и проверить изменения в валидации.

**Comment by danilastepanov** [comment]
Перепроверил, закрыл
