### ISSUE TITLE
Разработать фичу S.6.7. Приглашение специалиста в проект

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Backend#251]
Ссылка на требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.cqpre1qztbby

**Comment by Badmajor** [comment]
Можно реализовать через отдельную сущность/модель invite, которую можно создать, изменять и удалять по ручке /profile/invite. 

Так же нужен будет эндпоинт для прсомотра приглашений, как отправленных, так и поулченных, Думаю это будет отдельная вьюха с фильтром по полю приглашенный и приглашающий.

По сигналу при создании отправляется письмо приглашенному.

При принятии приглашения, проверяется есть ли свободное место в проете по этой профессии, в случае если мест уже нет, не добавляем, в противном случае добавляем его в проект.

 Поля:
- проект
- приглашающий
- приглашенный
~ответ (не просмотрено/принято/ отклонено)~
- статус ( актуально/ отменено) 
- время создания
- профессия

Вопросы: 
1. отдельная вьюха ли акшин?
2. отправлять письмо при изменении статуса? 
3. засунуть её в ~профили~ Проект?

**Comment by danilastepanov** [comment]
> Можно реализовать через отдельную сущность/модель invite, которую можно создать, изменять и удалять по ручке /profile/invite.
> 
> Так же нужен будет эндпоинт для прсомотра приглашений, как отправленных, так и поулченных, Думаю это будет отдельная вьюха с фильтром по полю приглашенный и приглашающий.
> 
> По сигналу при создании отправляется письмо приглашенному.
> 
> При принятии приглашения, проверяется есть ли свободное место в проете по этой профессии, в случае если мест уже нет, не добавляем, в противном случае добавляем его в проект.
> 
> Поля:
> 
> * проект
> * приглашающий
> * приглашенный
> * ответ (не просмотрено/принято/ отклонено)
> * статус ( актуально/ отменено)
> * время создания
> * профессия
> 
> Вопросы:
> 
> 1. отдельная вьюха ли акшин?
> 2. отправлять письмо при изменении статуса?
> 3. засунуть её в профили?

На собрании бэков нада это обсудить

**Comment by Badmajor** [comment]
Сделал ручку для создания, удаления и просмотра пригладений `projects/invitations`

Добавил валидацию при создании.

Осталось:
1.Отправка письма пользователю, если его приглашают
2. Редактирование статуса

**Comment by Badmajor** [comment]
Готово!
Для создания, удаления и просмотра приглашений `projects/invitations`
Данные валидируются. Проверяется, что проекту действительно требуется этот специалист, что пользователь не участвует в проекте, так же что у приглашенного есть подходящая специальность.

При принятии приглашения, изменении статуса на ACCEPTED, пользователь добавляется в проект. 

При создании приглашения пользователю отправляется письмо, что его приглашают в проект

**Comment by Badmajor** [comment]
@danilastepanov можно тестить
