### ISSUE TITLE
Разработать фичу P.5.2 Пагинация в разделе проектов

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Backend#28]
Ссылка на требования:
https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.nkhtrjnb54ni

**Comment by kseniia2673** [comment]
@ArtemKAF насколько понимаю, это реализовано Олесей и можно в дан переводить ?
