### ISSUE TITLE
PATCH /api/v1/profiles/me/specialists/{{id_spec}}/: Можно передать больше 15 навыков

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Backend#283]
### **Шаги воспроизведения:**

1. Отправить запрос на редактирование специалиста с 15ю навыками:
```
curl --location --request PATCH 'https://devcodepet.tw1.ru/api/v1/profiles/me/specialists/8/' \
--header 'Authorization: Token 394eea36788b945cfe7bd4c1452e03b8b3d2041d' \
--header 'Content-Type: application/json' \
--data '{
  "profession": 3,
  "level": 1,
  "skills": [
     1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
  ]
}'
```

### **Ожидаемый результат:**

Нельзя передать больше 15 навыков. Код и статус ответа 400 Bad request

### **Фактический результат:**

Можно передать больше 15 навыков. Код и статус ответа 200 OK

### **Окружение:**

* Сервер: [https://devcodepet.tw1.ru](https://devcodepet.tw1.ru/)
* Приложение: Postman v10.24.22
* ОС: Windows 11 22000.1098

**Comment by Badmajor** [comment]
Иправлено!

**Comment by danilastepanov** [comment]
Исправлено!
