### ISSUE TITLE
PATCH /api/v1/projects/{{id}}/: 500я ошибка при передаче тела без поля "started"

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Backend#324]
### Шаги воспроизведения:
Отправить запрос на редактирование проекта без поля "started":
```
curl --location --request PATCH 'https://devcodepet.tw1.ru/api/v1/projects/5/' \
--header 'Authorization: Token fa569889c0e606594941808c727cf60a39739787' \
--header 'Content-Type: application/json' \
--data '{
  "name": "гмД Ю"
}'
```
### Ожидаемый результат:
Код и статус ответа 200 ОК

### Фактический результат:
Код и статус ответа 500 Internal Server Error. Нельзя передать запрос без поля "started".

### Окружение:
Сервер: https://devcodepet.tw1.ru
Приложение: Postman v10.6.7
ОС: Windows 11 22000.1098

### Приложение:
![image](https://github.com/Pet-projects-CodePET/Backend/assets/32541462/2df87748-8326-4617-9c23-fd85d6349b8f)

**Comment by Badmajor** [comment]
@danilastepanov Проверяй
