### ISSUE TITLE
Добавить организатору проекта поля id, avatar, name, username из его профиля. Ручка /api/v1/projects/{id}/

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Backend#328]
![Image](https://github.com/Pet-projects-CodePET/Backend/assets/32541462/46e70504-c7ef-4997-92b9-cf1ce7c9cda6)

**Comment by Badmajor** [comment]
@danilastepanov организатор это создатель или хозяин? 
 или нужно добавить другую сущность?

**Comment by Badmajor** [comment]
@danilastepanov Проверяй
