### ISSUE TITLE
Добавить информацию о статусе видимости профиля для участников проекта и владельцу проекта (ручка get /api/v1/projects/id/)

### ISSUE THREAD

**Issue by danilastepanov** [Pet-projects-CodePET/Backend#380]
Добавить поле "visible_status" участникам проекта и владельцу проекта

![Image](https://github.com/user-attachments/assets/27178a46-fb6a-421a-a7b4-9964dfae9e98)

**Comment by Badmajor** [comment]
![изображение](https://github.com/user-attachments/assets/087cd568-e30c-472b-a7d1-fcad22ccd66c)
Добавил visible_status, точно такой же как в профиле
