### ISSUE TITLE
Разработать фичу G.1.1 Просмотр главной страницы

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Backend#6]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

- [x] #14 
- [x] #12 
- [x] #13

**Comment by kseniia2673** [comment]
- [ ] #8
