### ISSUE TITLE
Разработать фичу V.3.1 Авторизация по email

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Backend#7]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

реализовать с учетом того, что потребуется как авторизация при помощи (email/пароль) без участия соц. сетей, так и через них.
    библиотеки, которые могут пригодиться:
    rest-social-auth 8.3.0 - https://pypi.org/project/rest-social-auth/
    drf-social-oauth2 2.1.3 - https://drf-social-oauth2.readthedocs.io/en/latest/index.html
    django-allauth + django-rest-allauth - https://apirobot.me/posts/django-vue-google-auth

- [x] #9  
- [ ] API Авторизации

**Comment by kseniia2673** [comment]
#22
