### ISSUE TITLE
Разработать фичу R.2.1 регистрация пользователя по email

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/Backend#8]
Ссылка на фич лист:
https://docs.google.com/spreadsheets/d/1QXD36DZHGH-bGDUzqYXv3B9DDxJkbzYI0FapSGFM5vk/edit#gid=765184209

при реализации обратить особое внимание на валидацию email и password.

- [x] #9 
- [ ] API регистрации

**Comment by kseniia2673** [comment]
#22
